[book]
title = "gtirs-rb Documentation"
description = """
gtirs-rb is a Rust API for Intermediate Representation for Binary analysis and transformation (GTIRB).
It wraps a pretty-printer for displaying GTIRB in a human-readable format, a parser/writer for reading and writing GTIRB files, and methods for manipulating GTIRB objects.
This can serve as a foundation for building tools that analyze and transform binary programs.
"""
authors = ["abel"]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/docs/"
git-repository-url = "https://github.com/horde-re/gtirs-rb/tree/main/docs"
edit-url-template = "https://github.com/horde-re/gtirs-rb/edit/main/docs/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
