name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev", "feat/*", "fix/*", "doc/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Install probuf compiler
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: protobuf-compiler
          version: 1.0

    # Check format, lint code, build and test it 
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --verbose
    - name: Lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
